

DROP TABLE User_Info CASCADE CONSTRAINTS;

DROP TABLE Car CASCADE CONSTRAINTS;

DROP TABLE Interest CASCADE CONSTRAINTS;

DROP TABLE View_History CASCADE CONSTRAINTS;

DROP TABLE Order_History CASCADE CONSTRAINTS;

DROP TABLE Post CASCADE CONSTRAINTS;